modLoader="javafml"
loaderVersion="[38,41)"
license="All rights reserved"
issueTrackerURL="https://github.com/SrRapero720/CraftyTraceCrashes/issues" #optional


[[mods]] #mandatory
    modId="craftitrace" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="CraftITrace" #mandatory
    displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
    logoFile="pack.png" #optional
    credits="Created by Chocohead and comp500" #optional
    authors="Ported and maintained by SrRapero720" #optional
    description='''
    Port of MixinTrace and CraftyCrashes
    Trace mixins in crash report and replace
    target mixin class with broken mixin class

    Check also WATERCoRE to enhance your server,
    fix memory leaks and more!!
    '''


[[dependencies.craftitrace]] #optional
    modId="forge"
    mandatory=true
    versionRange="[38,41)"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftitrace]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
#[[dependencies.craftitrace]]
#    modId="watercore"
#    mandatory=false
#    versionRange="[1.4)"
#    ordering="NONE"
#    side="BOTH"
